//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  projects: Projects;
  projectsConnection: ProjectsConnection;
  experience: Experience;
  experienceConnection: ExperienceConnection;
  caseStudies: CaseStudies;
  caseStudiesConnection: CaseStudiesConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectsFilter>;
};


export type QueryExperienceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryExperienceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExperienceFilter>;
};


export type QueryCaseStudiesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCaseStudiesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CaseStudiesFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};

export type DocumentFilter = {
  projects?: InputMaybe<ProjectsFilter>;
  experience?: InputMaybe<ExperienceFilter>;
  caseStudies?: InputMaybe<CaseStudiesFilter>;
  pages?: InputMaybe<PagesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Projects | Experience | CaseStudies | Pages | Folder;

export type Projects = Node & Document & {
  __typename?: 'Projects';
  title_en: Scalars['String']['output'];
  title_pt: Scalars['String']['output'];
  description_en: Scalars['String']['output'];
  description_pt: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  thumbnail: Scalars['String']['output'];
  hoverLottie?: Maybe<Scalars['String']['output']>;
  hasCaseStudy?: Maybe<Scalars['Boolean']['output']>;
  sortOrder?: Maybe<Scalars['Float']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ProjectsFilter = {
  title_en?: InputMaybe<StringFilter>;
  title_pt?: InputMaybe<StringFilter>;
  description_en?: InputMaybe<StringFilter>;
  description_pt?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  hoverLottie?: InputMaybe<StringFilter>;
  hasCaseStudy?: InputMaybe<BooleanFilter>;
  sortOrder?: InputMaybe<NumberFilter>;
  draft?: InputMaybe<BooleanFilter>;
};

export type ProjectsConnectionEdges = {
  __typename?: 'ProjectsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projects>;
};

export type ProjectsConnection = Connection & {
  __typename?: 'ProjectsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectsConnectionEdges>>>;
};

export type Experience = Node & Document & {
  __typename?: 'Experience';
  company: Scalars['String']['output'];
  role_en: Scalars['String']['output'];
  role_pt: Scalars['String']['output'];
  period_en: Scalars['String']['output'];
  period_pt: Scalars['String']['output'];
  sortOrder?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ExperienceFilter = {
  company?: InputMaybe<StringFilter>;
  role_en?: InputMaybe<StringFilter>;
  role_pt?: InputMaybe<StringFilter>;
  period_en?: InputMaybe<StringFilter>;
  period_pt?: InputMaybe<StringFilter>;
  sortOrder?: InputMaybe<NumberFilter>;
};

export type ExperienceConnectionEdges = {
  __typename?: 'ExperienceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Experience>;
};

export type ExperienceConnection = Connection & {
  __typename?: 'ExperienceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ExperienceConnectionEdges>>>;
};

export type CaseStudies = Node & Document & {
  __typename?: 'CaseStudies';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  role: Scalars['String']['output'];
  goal: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  externalHref?: Maybe<Scalars['String']['output']>;
  hideOtherProjects?: Maybe<Scalars['Boolean']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CaseStudiesBodyMetricsItemsFilter = {
  variant?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type CaseStudiesBodyMetricsFilter = {
  id?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  layout?: InputMaybe<StringFilter>;
  disclaimer?: InputMaybe<StringFilter>;
  items?: InputMaybe<CaseStudiesBodyMetricsItemsFilter>;
};

export type CaseStudiesBodyProblemsItemsFilter = {
  variant?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type CaseStudiesBodyProblemsFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  items?: InputMaybe<CaseStudiesBodyProblemsItemsFilter>;
};

export type CaseStudiesBodyResultsItemsFilter = {
  variant?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type CaseStudiesBodyResultsFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  disclaimer?: InputMaybe<StringFilter>;
  items?: InputMaybe<CaseStudiesBodyResultsItemsFilter>;
};

export type CaseStudiesBodyCaseImageFilter = {
  id?: InputMaybe<StringFilter>;
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  priority?: InputMaybe<BooleanFilter>;
  rounded?: InputMaybe<BooleanFilter>;
};

export type CaseStudiesBodyImageStackImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type CaseStudiesBodyImageStackFilter = {
  id?: InputMaybe<StringFilter>;
  images?: InputMaybe<CaseStudiesBodyImageStackImagesFilter>;
};

export type CaseStudiesBodyImageGridImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type CaseStudiesBodyImageGridFilter = {
  id?: InputMaybe<StringFilter>;
  images?: InputMaybe<CaseStudiesBodyImageGridImagesFilter>;
};

export type CaseStudiesBodyFilter = {
  Metrics?: InputMaybe<CaseStudiesBodyMetricsFilter>;
  Problems?: InputMaybe<CaseStudiesBodyProblemsFilter>;
  Results?: InputMaybe<CaseStudiesBodyResultsFilter>;
  CaseImage?: InputMaybe<CaseStudiesBodyCaseImageFilter>;
  ImageStack?: InputMaybe<CaseStudiesBodyImageStackFilter>;
  ImageGrid?: InputMaybe<CaseStudiesBodyImageGridFilter>;
};

export type CaseStudiesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  goal?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  externalHref?: InputMaybe<StringFilter>;
  hideOtherProjects?: InputMaybe<BooleanFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<CaseStudiesBodyFilter>;
};

export type CaseStudiesConnectionEdges = {
  __typename?: 'CaseStudiesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<CaseStudies>;
};

export type CaseStudiesConnection = Connection & {
  __typename?: 'CaseStudiesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CaseStudiesConnectionEdges>>>;
};

export type Pages = Node & Document & {
  __typename?: 'Pages';
  greeting_en: Scalars['String']['output'];
  greeting_pt: Scalars['String']['output'];
  bio_en?: Maybe<Scalars['String']['output']>;
  bio_pt?: Maybe<Scalars['String']['output']>;
  resumeLabel_en?: Maybe<Scalars['String']['output']>;
  resumeLabel_pt?: Maybe<Scalars['String']['output']>;
  profilePic?: Maybe<Scalars['String']['output']>;
  resumePdf_en?: Maybe<Scalars['String']['output']>;
  resumePdf_pt?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesFilter = {
  greeting_en?: InputMaybe<StringFilter>;
  greeting_pt?: InputMaybe<StringFilter>;
  bio_en?: InputMaybe<StringFilter>;
  bio_pt?: InputMaybe<StringFilter>;
  resumeLabel_en?: InputMaybe<StringFilter>;
  resumeLabel_pt?: InputMaybe<StringFilter>;
  profilePic?: InputMaybe<ImageFilter>;
  resumePdf_en?: InputMaybe<StringFilter>;
  resumePdf_pt?: InputMaybe<StringFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProjects: Projects;
  createProjects: Projects;
  updateExperience: Experience;
  createExperience: Experience;
  updateCaseStudies: CaseStudies;
  createCaseStudies: CaseStudies;
  updatePages: Pages;
  createPages: Pages;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectsMutation;
};


export type MutationCreateProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectsMutation;
};


export type MutationUpdateExperienceArgs = {
  relativePath: Scalars['String']['input'];
  params: ExperienceMutation;
};


export type MutationCreateExperienceArgs = {
  relativePath: Scalars['String']['input'];
  params: ExperienceMutation;
};


export type MutationUpdateCaseStudiesArgs = {
  relativePath: Scalars['String']['input'];
  params: CaseStudiesMutation;
};


export type MutationCreateCaseStudiesArgs = {
  relativePath: Scalars['String']['input'];
  params: CaseStudiesMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};

export type DocumentUpdateMutation = {
  projects?: InputMaybe<ProjectsMutation>;
  experience?: InputMaybe<ExperienceMutation>;
  caseStudies?: InputMaybe<CaseStudiesMutation>;
  pages?: InputMaybe<PagesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  projects?: InputMaybe<ProjectsMutation>;
  experience?: InputMaybe<ExperienceMutation>;
  caseStudies?: InputMaybe<CaseStudiesMutation>;
  pages?: InputMaybe<PagesMutation>;
};

export type ProjectsMutation = {
  title_en?: InputMaybe<Scalars['String']['input']>;
  title_pt?: InputMaybe<Scalars['String']['input']>;
  description_en?: InputMaybe<Scalars['String']['input']>;
  description_pt?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  hoverLottie?: InputMaybe<Scalars['String']['input']>;
  hasCaseStudy?: InputMaybe<Scalars['Boolean']['input']>;
  sortOrder?: InputMaybe<Scalars['Float']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ExperienceMutation = {
  company?: InputMaybe<Scalars['String']['input']>;
  role_en?: InputMaybe<Scalars['String']['input']>;
  role_pt?: InputMaybe<Scalars['String']['input']>;
  period_en?: InputMaybe<Scalars['String']['input']>;
  period_pt?: InputMaybe<Scalars['String']['input']>;
  sortOrder?: InputMaybe<Scalars['Float']['input']>;
};

export type CaseStudiesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  goal?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  externalHref?: InputMaybe<Scalars['String']['input']>;
  hideOtherProjects?: InputMaybe<Scalars['Boolean']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PagesMutation = {
  greeting_en?: InputMaybe<Scalars['String']['input']>;
  greeting_pt?: InputMaybe<Scalars['String']['input']>;
  bio_en?: InputMaybe<Scalars['String']['input']>;
  bio_pt?: InputMaybe<Scalars['String']['input']>;
  resumeLabel_en?: InputMaybe<Scalars['String']['input']>;
  resumeLabel_pt?: InputMaybe<Scalars['String']['input']>;
  profilePic?: InputMaybe<Scalars['String']['input']>;
  resumePdf_en?: InputMaybe<Scalars['String']['input']>;
  resumePdf_pt?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectsPartsFragment = { __typename: 'Projects', title_en: string, title_pt: string, description_en: string, description_pt: string, slug: string, thumbnail: string, hoverLottie?: string | null, hasCaseStudy?: boolean | null, sortOrder?: number | null, draft?: boolean | null };

export type ExperiencePartsFragment = { __typename: 'Experience', company: string, role_en: string, role_pt: string, period_en: string, period_pt: string, sortOrder?: number | null };

export type CaseStudiesPartsFragment = { __typename: 'CaseStudies', title: string, description: string, role: string, goal: string, slug: string, externalHref?: string | null, hideOtherProjects?: boolean | null, draft?: boolean | null, body?: any | null };

export type PagesPartsFragment = { __typename: 'Pages', greeting_en: string, greeting_pt: string, bio_en?: string | null, bio_pt?: string | null, resumeLabel_en?: string | null, resumeLabel_pt?: string | null, profilePic?: string | null, resumePdf_en?: string | null, resumePdf_pt?: string | null };

export type ProjectsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectsQuery = { __typename?: 'Query', projects: { __typename: 'Projects', id: string, title_en: string, title_pt: string, description_en: string, description_pt: string, slug: string, thumbnail: string, hoverLottie?: string | null, hasCaseStudy?: boolean | null, sortOrder?: number | null, draft?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjectsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectsFilter>;
}>;


export type ProjectsConnectionQuery = { __typename?: 'Query', projectsConnection: { __typename?: 'ProjectsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectsConnectionEdges', cursor: string, node?: { __typename: 'Projects', id: string, title_en: string, title_pt: string, description_en: string, description_pt: string, slug: string, thumbnail: string, hoverLottie?: string | null, hasCaseStudy?: boolean | null, sortOrder?: number | null, draft?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ExperienceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ExperienceQuery = { __typename?: 'Query', experience: { __typename: 'Experience', id: string, company: string, role_en: string, role_pt: string, period_en: string, period_pt: string, sortOrder?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ExperienceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExperienceFilter>;
}>;


export type ExperienceConnectionQuery = { __typename?: 'Query', experienceConnection: { __typename?: 'ExperienceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ExperienceConnectionEdges', cursor: string, node?: { __typename: 'Experience', id: string, company: string, role_en: string, role_pt: string, period_en: string, period_pt: string, sortOrder?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type CaseStudiesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CaseStudiesQuery = { __typename?: 'Query', caseStudies: { __typename: 'CaseStudies', id: string, title: string, description: string, role: string, goal: string, slug: string, externalHref?: string | null, hideOtherProjects?: boolean | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type CaseStudiesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CaseStudiesFilter>;
}>;


export type CaseStudiesConnectionQuery = { __typename?: 'Query', caseStudiesConnection: { __typename?: 'CaseStudiesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CaseStudiesConnectionEdges', cursor: string, node?: { __typename: 'CaseStudies', id: string, title: string, description: string, role: string, goal: string, slug: string, externalHref?: string | null, hideOtherProjects?: boolean | null, draft?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename: 'Pages', id: string, greeting_en: string, greeting_pt: string, bio_en?: string | null, bio_pt?: string | null, resumeLabel_en?: string | null, resumeLabel_pt?: string | null, profilePic?: string | null, resumePdf_en?: string | null, resumePdf_pt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagesConnectionEdges', cursor: string, node?: { __typename: 'Pages', id: string, greeting_en: string, greeting_pt: string, bio_en?: string | null, bio_pt?: string | null, resumeLabel_en?: string | null, resumeLabel_pt?: string | null, profilePic?: string | null, resumePdf_en?: string | null, resumePdf_pt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ProjectsPartsFragmentDoc = gql`
    fragment ProjectsParts on Projects {
  __typename
  title_en
  title_pt
  description_en
  description_pt
  slug
  thumbnail
  hoverLottie
  hasCaseStudy
  sortOrder
  draft
}
    `;
export const ExperiencePartsFragmentDoc = gql`
    fragment ExperienceParts on Experience {
  __typename
  company
  role_en
  role_pt
  period_en
  period_pt
  sortOrder
}
    `;
export const CaseStudiesPartsFragmentDoc = gql`
    fragment CaseStudiesParts on CaseStudies {
  __typename
  title
  description
  role
  goal
  slug
  externalHref
  hideOtherProjects
  draft
  body
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  greeting_en
  greeting_pt
  bio_en
  bio_pt
  resumeLabel_en
  resumeLabel_pt
  profilePic
  resumePdf_en
  resumePdf_pt
}
    `;
export const ProjectsDocument = gql`
    query projects($relativePath: String!) {
  projects(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectsParts
  }
}
    ${ProjectsPartsFragmentDoc}`;
export const ProjectsConnectionDocument = gql`
    query projectsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectsFilter) {
  projectsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectsParts
      }
    }
  }
}
    ${ProjectsPartsFragmentDoc}`;
export const ExperienceDocument = gql`
    query experience($relativePath: String!) {
  experience(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ExperienceParts
  }
}
    ${ExperiencePartsFragmentDoc}`;
export const ExperienceConnectionDocument = gql`
    query experienceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ExperienceFilter) {
  experienceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ExperienceParts
      }
    }
  }
}
    ${ExperiencePartsFragmentDoc}`;
export const CaseStudiesDocument = gql`
    query caseStudies($relativePath: String!) {
  caseStudies(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CaseStudiesParts
  }
}
    ${CaseStudiesPartsFragmentDoc}`;
export const CaseStudiesConnectionDocument = gql`
    query caseStudiesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CaseStudiesFilter) {
  caseStudiesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CaseStudiesParts
      }
    }
  }
}
    ${CaseStudiesPartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      projects(variables: ProjectsQueryVariables, options?: C): Promise<{data: ProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsQueryVariables, query: string}> {
        return requester<{data: ProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsQueryVariables, query: string}, ProjectsQueryVariables>(ProjectsDocument, variables, options);
      },
    projectsConnection(variables?: ProjectsConnectionQueryVariables, options?: C): Promise<{data: ProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsConnectionQueryVariables, query: string}, ProjectsConnectionQueryVariables>(ProjectsConnectionDocument, variables, options);
      },
    experience(variables: ExperienceQueryVariables, options?: C): Promise<{data: ExperienceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceQueryVariables, query: string}> {
        return requester<{data: ExperienceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceQueryVariables, query: string}, ExperienceQueryVariables>(ExperienceDocument, variables, options);
      },
    experienceConnection(variables?: ExperienceConnectionQueryVariables, options?: C): Promise<{data: ExperienceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceConnectionQueryVariables, query: string}> {
        return requester<{data: ExperienceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceConnectionQueryVariables, query: string}, ExperienceConnectionQueryVariables>(ExperienceConnectionDocument, variables, options);
      },
    caseStudies(variables: CaseStudiesQueryVariables, options?: C): Promise<{data: CaseStudiesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudiesQueryVariables, query: string}> {
        return requester<{data: CaseStudiesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudiesQueryVariables, query: string}, CaseStudiesQueryVariables>(CaseStudiesDocument, variables, options);
      },
    caseStudiesConnection(variables?: CaseStudiesConnectionQueryVariables, options?: C): Promise<{data: CaseStudiesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudiesConnectionQueryVariables, query: string}> {
        return requester<{data: CaseStudiesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudiesConnectionQueryVariables, query: string}, CaseStudiesConnectionQueryVariables>(CaseStudiesConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  