import type { Deal } from './types';

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-1',
    clientName: 'Marília Gonçalves Ramos',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-marilia.png',
    stage: 'aguardando',
    statusLabel: 'Aguardando',
    dueLabel: 'Em 7 dias',
    dueUrgency: 'normal',
    mainProduct: 'Trilogia Russell Brunson - Segredos',
    extraProductsCount: 2,
    totalValue: 1997,
    totalValueFormatted: 'R$ 1.997,00',
    commission: 297,
    commissionFormatted: 'R$ 297,00',
    startDate: '13 Jan',
    platform: 'Hotmart',
    phone: '+55 11 98765-4321',
    email: 'marilia.ramos@email.com',
    createdAtDaysAgo: 7,
    cartProducts: [
      {
        id: 'p1',
        name: 'Método Speed English',
        status: 'Aguardando Contato',
        price: 1997,
        priceFormatted: 'R$ 1.997,00',
        commission: 297,
        commissionFormatted: 'R$ 297,00',
        date: '13 Jan',
      },
      {
        id: 'p2',
        name: 'Trilogia Russell Brunson - Segredos',
        status: 'Adicionado ao Carrinho',
        price: 378,
        priceFormatted: 'R$ 378,00',
        commission: 56,
        commissionFormatted: 'R$ 56,00',
        date: '09 Jan',
      },
      {
        id: 'p3',
        name: 'Curso de Copywriting Avançado',
        status: 'Em Andamento',
        price: 1200,
        priceFormatted: 'R$ 1.200,00',
        commission: 180,
        commissionFormatted: 'R$ 180,00',
        date: '15 Jan',
      },
    ],
    activities: [
      {
        date: '17/07',
        countLabel: '1 atividade',
        events: [
          {
            id: 'e1',
            type: 'compra_concluida',
            title: 'Compra Concluída',
            time: '08:40',
            actor: 'Usuário',
            action: 'Pagamento de R$ 1.997 aprovado via Pix',
          },
        ],
      },
      {
        date: '17/07',
        countLabel: '2 atividades',
        events: [
          {
            id: 'e2',
            type: 'compra_iniciada',
            title: 'Compra Iniciada',
            time: '08:35',
            actor: 'Sistema',
            action: 'Checkout aberto pelo link de recuperação',
          },
          {
            id: 'e3',
            type: 'compra_expirada',
            title: 'Compra Expirada',
            time: '08:00',
            actor: 'Usuário',
            action: 'Código Pix anterior expirou sem pagamento',
          },
        ],
      },
      {
        date: '16/07',
        countLabel: '2 atividades',
        events: [
          {
            id: 'e4',
            type: 'compra_cancelada',
            title: 'Compra Cancelada',
            time: '19:42',
            actor: 'Sistema',
            action: 'Tentativa com cartão recusada pela operadora',
          },
          {
            id: 'e5',
            type: 'email_enviado',
            title: 'E-mail Enviado',
            time: '19:40',
            actor: 'Usuário',
            action: 'Disparo de e-mail automático com desconto de 10%',
          },
        ],
      },
      {
        date: '15/07',
        countLabel: '1 atividade',
        events: [
          {
            id: 'e6',
            type: 'whatsapp_enviado',
            title: 'WhatsApp Enviado',
            time: '14:20',
            actor: 'Sistema',
            action: 'Mensagem de recuperação enviada via Vendd Bot',
          },
        ],
      },
    ],
    chatHistory: [
      {
        id: 'c1',
        sender: 'bot',
        text: 'Olá Marília! Notamos que você iniciou sua inscrição na Trilogia Russell Brunson, mas não concluiu. Ficou alguma dúvida sobre o conteúdo ou condições?',
        time: '14:20',
        status: 'read',
      },
      {
        id: 'c2',
        sender: 'lead',
        text: 'Oi! Meu cartão deu erro na hora de passar. Vocês aceitam Pix com algum desconto?',
        time: '14:32',
      },
      {
        id: 'c3',
        sender: 'agent',
        text: 'Olá Marília! Sim, conseguimos gerar um código Pix direto com 5% de desconto especial agora mesmo. Segue o link com valor atualizado: vendd.link/recuperar-pix-992',
        time: '14:35',
        status: 'read',
      },
    ],
  },
  {
    id: 'deal-2',
    clientName: 'João da Silva Santos',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-joao.png',
    stage: 'aguardando',
    statusLabel: 'Aguardando',
    dueLabel: 'Hoje',
    dueUrgency: 'urgent',
    mainProduct: 'English Speed Faster',
    extraProductsCount: 1,
    totalValue: 2497,
    totalValueFormatted: 'R$ 2.497,00',
    commission: 374,
    commissionFormatted: 'R$ 374,00',
    startDate: '14 Jan',
    platform: 'Kiwify',
    phone: '+55 21 97654-3210',
    email: 'joao.silva@email.com',
    createdAtDaysAgo: 3,
    cartProducts: [
      {
        id: 'p4',
        name: 'English Speed Faster',
        status: 'Aguardando Contato',
        price: 2497,
        priceFormatted: 'R$ 2.497,00',
        commission: 374,
        commissionFormatted: 'R$ 374,00',
        date: '14 Jan',
      },
      {
        id: 'p5',
        name: 'Acelerador de Vocabulário',
        status: 'Adicionado ao Carrinho',
        price: 297,
        priceFormatted: 'R$ 297,00',
        commission: 45,
        commissionFormatted: 'R$ 45,00',
        date: '14 Jan',
      },
    ],
    activities: [
      {
        date: '14/01',
        countLabel: '1 atividade',
        events: [
          {
            id: 'e7',
            type: 'compra_iniciada',
            title: 'Compra Iniciada',
            time: '11:15',
            actor: 'Sistema',
            action: 'Checkout aberto pelo usuário',
          },
        ],
      },
    ],
    chatHistory: [
      {
        id: 'c4',
        sender: 'bot',
        text: 'Oi João! Tudo bem? Vi que você estava quase entrando para a turma do English Speed Faster. Posso te ajudar a garantir sua vaga?',
        time: '11:30',
        status: 'delivered',
      },
    ],
  },
  {
    id: 'deal-3',
    clientName: 'Maria Clara Oliveira',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-maria.png',
    stage: 'aguardando',
    statusLabel: 'Aguardando',
    dueLabel: 'Há 3 dias',
    dueUrgency: 'warning',
    mainProduct: 'Accelerate Your English Skills',
    extraProductsCount: 1,
    totalValue: 797,
    totalValueFormatted: 'R$ 797,00',
    commission: 119,
    commissionFormatted: 'R$ 119,00',
    startDate: '10 Jan',
    platform: 'Vendd Pay',
    phone: '+55 31 99876-5432',
    email: 'maria.clara@email.com',
    createdAtDaysAgo: 5,
    cartProducts: [
      {
        id: 'p6',
        name: 'Accelerate Your English Skills',
        status: 'Aguardando Contato',
        price: 797,
        priceFormatted: 'R$ 797,00',
        commission: 119,
        commissionFormatted: 'R$ 119,00',
        date: '10 Jan',
      },
    ],
    activities: [
      {
        date: '10/01',
        countLabel: '1 atividade',
        events: [
          {
            id: 'e8',
            type: 'compra_expirada',
            title: 'Compra Expirada',
            time: '16:00',
            actor: 'Usuário',
            action: 'Boleto bancário venceu sem confirmação de pagamento',
          },
        ],
      },
    ],
    chatHistory: [],
  },
  {
    id: 'deal-4',
    clientName: 'Carlos Alberto Pereira',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-carlos.png',
    stage: 'aguardando',
    statusLabel: 'Aguardando',
    dueLabel: 'Em 2 dias',
    dueUrgency: 'normal',
    mainProduct: 'Boost Your English Proficiency',
    extraProductsCount: 1,
    totalValue: 497,
    totalValueFormatted: 'R$ 497,00',
    commission: 74,
    commissionFormatted: 'R$ 74,00',
    startDate: '15 Jan',
    platform: 'Hotmart',
    phone: '+55 41 98888-7777',
    email: 'carlos.pereira@email.com',
    createdAtDaysAgo: 2,
    cartProducts: [
      {
        id: 'p7',
        name: 'Boost Your English Proficiency',
        status: 'Aguardando Contato',
        price: 497,
        priceFormatted: 'R$ 497,00',
        commission: 74,
        commissionFormatted: 'R$ 74,00',
        date: '15 Jan',
      },
    ],
    activities: [],
    chatHistory: [],
  },
  {
    id: 'deal-5',
    clientName: 'Ana Beatriz Costa',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-ana.png',
    stage: 'contato_realizado',
    statusLabel: 'Contato Realizado',
    dueLabel: 'Hoje',
    dueUrgency: 'urgent',
    mainProduct: 'Trilogia Russell Brunson - Segredos',
    extraProductsCount: 2,
    totalValue: 1997,
    totalValueFormatted: 'R$ 1.997,00',
    commission: 297,
    commissionFormatted: 'R$ 297,00',
    startDate: '12 Jan',
    platform: 'Hotmart',
    phone: '+55 19 99123-4567',
    email: 'ana.costa@email.com',
    createdAtDaysAgo: 6,
    cartProducts: [
      {
        id: 'p8',
        name: 'Trilogia Russell Brunson - Segredos',
        status: 'Em Andamento',
        price: 1997,
        priceFormatted: 'R$ 1.997,00',
        commission: 297,
        commissionFormatted: 'R$ 297,00',
        date: '12 Jan',
      },
    ],
    activities: [
      {
        date: '12/01',
        countLabel: '1 atividade',
        events: [
          {
            id: 'e9',
            type: 'whatsapp_enviado',
            title: 'WhatsApp Enviado',
            time: '10:00',
            actor: 'Usuário',
            action: 'Conversa iniciada com operador humano',
          },
        ],
      },
    ],
    chatHistory: [],
  },
  {
    id: 'deal-6',
    clientName: 'Gustavo Henrique Martins',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-gustavo.png',
    stage: 'contato_realizado',
    statusLabel: 'Contato Realizado',
    dueLabel: 'Há 8 dias',
    dueUrgency: 'warning',
    mainProduct: 'Boost Your English Proficiency',
    extraProductsCount: 1,
    totalValue: 497,
    totalValueFormatted: 'R$ 497,00',
    commission: 74,
    commissionFormatted: 'R$ 74,00',
    startDate: '08 Jan',
    platform: 'Kiwify',
    phone: '+55 51 98111-2233',
    email: 'gustavo.martins@email.com',
    createdAtDaysAgo: 10,
    cartProducts: [
      {
        id: 'p9',
        name: 'Boost Your English Proficiency',
        status: 'Em Andamento',
        price: 497,
        priceFormatted: 'R$ 497,00',
        commission: 74,
        commissionFormatted: 'R$ 74,00',
        date: '08 Jan',
      },
    ],
    activities: [],
    chatHistory: [],
  },
  {
    id: 'deal-7',
    clientName: 'Ricardo Almeida Ferreira',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-ricardo.png',
    stage: 'contato_realizado',
    statusLabel: 'Contato Realizado',
    dueLabel: 'Há 2 dias',
    dueUrgency: 'normal',
    mainProduct: 'English Speed Faster',
    extraProductsCount: 1,
    totalValue: 2497,
    totalValueFormatted: 'R$ 2.497,00',
    commission: 374,
    commissionFormatted: 'R$ 374,00',
    startDate: '11 Jan',
    platform: 'Vendd Pay',
    phone: '+55 61 99234-5678',
    email: 'ricardo.ferreira@email.com',
    createdAtDaysAgo: 8,
    cartProducts: [
      {
        id: 'p10',
        name: 'English Speed Faster',
        status: 'Em Andamento',
        price: 2497,
        priceFormatted: 'R$ 2.497,00',
        commission: 374,
        commissionFormatted: 'R$ 374,00',
        date: '11 Jan',
      },
    ],
    activities: [],
    chatHistory: [],
  },
  {
    id: 'deal-8',
    clientName: 'Fernanda Lima Santos',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-fernanda.png',
    stage: 'contato_realizado',
    statusLabel: 'Contato Realizado',
    dueLabel: 'Hoje',
    dueUrgency: 'urgent',
    mainProduct: 'Accelerate Your English Skills',
    extraProductsCount: 1,
    totalValue: 797,
    totalValueFormatted: 'R$ 797,00',
    commission: 119,
    commissionFormatted: 'R$ 119,00',
    startDate: '13 Jan',
    platform: 'Hotmart',
    phone: '+55 71 99345-6789',
    email: 'fernanda.santos@email.com',
    createdAtDaysAgo: 4,
    cartProducts: [
      {
        id: 'p11',
        name: 'Accelerate Your English Skills',
        status: 'Em Andamento',
        price: 797,
        priceFormatted: 'R$ 797,00',
        commission: 119,
        commissionFormatted: 'R$ 119,00',
        date: '13 Jan',
      },
    ],
    activities: [],
    chatHistory: [],
  },
  {
    id: 'deal-9',
    clientName: 'Leonardo Pereira Gomes',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-leonardo.png',
    stage: 'reuniao_agendada',
    statusLabel: 'Reunião Agendada',
    dueLabel: 'Há 1 dia',
    dueUrgency: 'normal',
    mainProduct: 'Boost Your English Proficiency',
    extraProductsCount: 1,
    totalValue: 497,
    totalValueFormatted: 'R$ 497,00',
    commission: 74,
    commissionFormatted: 'R$ 74,00',
    startDate: '16 Jan',
    platform: 'Hotmart',
    phone: '+55 81 99456-7890',
    email: 'leonardo.gomes@email.com',
    createdAtDaysAgo: 3,
    cartProducts: [
      {
        id: 'p12',
        name: 'Boost Your English Proficiency',
        status: 'Em Andamento',
        price: 497,
        priceFormatted: 'R$ 497,00',
        commission: 74,
        commissionFormatted: 'R$ 74,00',
        date: '16 Jan',
      },
    ],
    activities: [],
    chatHistory: [],
  },
  {
    id: 'deal-10',
    clientName: 'Felipe Augusto Mendes',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-felipe.png',
    stage: 'reuniao_agendada',
    statusLabel: 'Reunião Agendada',
    dueLabel: 'Em 2 dias',
    dueUrgency: 'normal',
    mainProduct: 'English Speed Faster',
    extraProductsCount: 1,
    totalValue: 2497,
    totalValueFormatted: 'R$ 2.497,00',
    commission: 374,
    commissionFormatted: 'R$ 374,00',
    startDate: '14 Jan',
    platform: 'Kiwify',
    phone: '+55 85 99567-8901',
    email: 'felipe.mendes@email.com',
    createdAtDaysAgo: 4,
    cartProducts: [
      {
        id: 'p13',
        name: 'English Speed Faster',
        status: 'Em Andamento',
        price: 2497,
        priceFormatted: 'R$ 2.497,00',
        commission: 374,
        commissionFormatted: 'R$ 374,00',
        date: '14 Jan',
      },
    ],
    activities: [],
    chatHistory: [],
  },
  {
    id: 'deal-11',
    clientName: 'Isabela Rodrigues Lima',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-isabela.png',
    stage: 'reuniao_agendada',
    statusLabel: 'Reunião Agendada',
    dueLabel: 'Hoje',
    dueUrgency: 'urgent',
    mainProduct: 'Trilogia Russell Brunson - Segredos',
    extraProductsCount: 2,
    totalValue: 1997,
    totalValueFormatted: 'R$ 1.997,00',
    commission: 297,
    commissionFormatted: 'R$ 297,00',
    startDate: '13 Jan',
    platform: 'Hotmart',
    phone: '+55 91 99678-9012',
    email: 'isabela.lima@email.com',
    createdAtDaysAgo: 5,
    cartProducts: [
      {
        id: 'p14',
        name: 'Trilogia Russell Brunson - Segredos',
        status: 'Em Andamento',
        price: 1997,
        priceFormatted: 'R$ 1.997,00',
        commission: 297,
        commissionFormatted: 'R$ 297,00',
        date: '13 Jan',
      },
    ],
    activities: [],
    chatHistory: [],
  },
  {
    id: 'deal-12',
    clientName: 'Tatiane dos Santos Silva',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-tatiane.png',
    stage: 'reuniao_agendada',
    statusLabel: 'Reunião Agendada',
    dueLabel: 'Há 3 dias',
    dueUrgency: 'warning',
    mainProduct: 'Accelerate Your English Skills',
    extraProductsCount: 1,
    totalValue: 797,
    totalValueFormatted: 'R$ 797,00',
    commission: 119,
    commissionFormatted: 'R$ 119,00',
    startDate: '09 Jan',
    platform: 'Vendd Pay',
    phone: '+55 48 99789-0123',
    email: 'tatiane.silva@email.com',
    createdAtDaysAgo: 9,
    cartProducts: [
      {
        id: 'p15',
        name: 'Accelerate Your English Skills',
        status: 'Em Andamento',
        price: 797,
        priceFormatted: 'R$ 797,00',
        commission: 119,
        commissionFormatted: 'R$ 119,00',
        date: '09 Jan',
      },
    ],
    activities: [],
    chatHistory: [],
  },
  {
    id: 'deal-diego',
    clientName: 'Diego Soares',
    avatarUrl: '/files/cases/vendd-web/avatars/avatar-carlos.png',
    stage: 'aguardando',
    statusLabel: 'Aguardando',
    dueLabel: 'Hoje',
    dueUrgency: 'urgent',
    mainProduct: 'Mentoria de Marketing Digital',
    extraProductsCount: 3,
    totalValue: 5997,
    totalValueFormatted: 'R$ 5.997,00',
    commission: 899,
    commissionFormatted: 'R$ 899,00',
    startDate: '17 Jul',
    platform: 'Vendd Pay',
    phone: '+55 11 99999-8888',
    email: 'diego.soares@email.com',
    createdAtDaysAgo: 7,
    cartProducts: [
      {
        id: 'dp1',
        name: 'Método Speed English',
        status: 'Aguardando Contato',
        price: 1997,
        priceFormatted: 'R$ 1.997,00',
        commission: 297,
        commissionFormatted: 'R$ 297,00',
        date: '17 Jul',
      },
      {
        id: 'dp2',
        name: 'Trilogia Russell Brunson - Segredos',
        status: 'Adicionado ao Carrinho',
        price: 378,
        priceFormatted: 'R$ 378,00',
        commission: 56,
        commissionFormatted: 'R$ 56,00',
        date: '16 Jul',
      },
      {
        id: 'dp3',
        name: 'Curso de Copywriting Avançado',
        status: 'Em Andamento',
        price: 1200,
        priceFormatted: 'R$ 1.200,00',
        commission: 180,
        commissionFormatted: 'R$ 180,00',
        date: '16 Jul',
      },
      {
        id: 'dp4',
        name: 'Mentoria de Marketing Digital',
        status: 'Finalizado',
        price: 2500,
        priceFormatted: 'R$ 2.500,00',
        commission: 375,
        commissionFormatted: 'R$ 375,00',
        date: '17 Jul',
      },
    ],
    activities: [
      {
        date: '17/07',
        countLabel: '1 atividade',
        events: [
          {
            id: 'de1',
            type: 'compra_concluida',
            title: 'Compra Concluída',
            time: '08:40',
            actor: 'Usuário',
            action: 'Pagamento de R$ 5.997 aprovado via Pix',
          },
        ],
      },
      {
        date: '17/07',
        countLabel: '2 atividades',
        events: [
          {
            id: 'de2',
            type: 'compra_iniciada',
            title: 'Compra Iniciada',
            time: '08:35',
            actor: 'Sistema',
            action: 'Checkout aberto pelo link de recuperação',
          },
          {
            id: 'de3',
            type: 'compra_expirada',
            title: 'Compra Expirada',
            time: '08:00',
            actor: 'Usuário',
            action: 'Código Pix anterior expirou',
          },
        ],
      },
      {
        date: '16/07',
        countLabel: '2 atividades',
        events: [
          {
            id: 'de4',
            type: 'compra_cancelada',
            title: 'Compra Cancelada',
            time: '19:42',
            actor: 'Sistema',
            action: 'Tentativa de cartão recusada',
          },
          {
            id: 'de5',
            type: 'email_enviado',
            title: 'E-mail Enviado',
            time: '19:40',
            actor: 'Usuário',
            action: 'E-mail enviado com cupom de recuperação',
          },
        ],
      },
      {
        date: '15/07',
        countLabel: '1 atividade',
        events: [
          {
            id: 'de6',
            type: 'whatsapp_enviado',
            title: 'WhatsApp Enviado',
            time: '14:20',
            actor: 'Sistema',
            action: 'Notificação automática enviada',
          },
        ],
      },
      {
        date: '15/07',
        countLabel: '1 atividade',
        events: [
          {
            id: 'de7',
            type: 'padrao',
            title: 'Padrão / Outros',
            time: '08:40',
            actor: 'Usuário',
            action: 'Lead capturado na página de vendas',
          },
        ],
      },
    ],
    chatHistory: [
      {
        id: 'dc1',
        sender: 'bot',
        text: 'Olá Diego! Notamos seu interesse na Mentoria e nos cursos da Vendd. Podemos te ajudar com alguma condição especial?',
        time: '08:15',
        status: 'read',
      },
      {
        id: 'dc2',
        sender: 'lead',
        text: 'Bom dia! Meu limite no cartão não autorizou o valor total. Vocês conseguem parcelar no Pix ou dividir em 2 cartões?',
        time: '08:22',
      },
      {
        id: 'dc3',
        sender: 'agent',
        text: 'Perfeito Diego! Conseguimos ativar a opção de pagamento em 2 cartões ou gerar uma entrada via Pix + restante. Segue o link liberado: vendd.link/checkout-flex-5997',
        time: '08:28',
        status: 'read',
      },
    ],
  },
];
